Algoritmo "carro"
// Disciplina   : [PA]
// Professor   : Cintia Pinho
// Autor(a)    : Isadora Walesca Alves Duarte
// Data atual  : 24/09/2021
Var
idade: inteiro
resp:caracter


Inicio
//entrada
escreval("qual a sua idade:")
leia(idade)

escreval("Possui habilitação:")
leia (resp)

//decisão

se ((idade>=18) e (resp="sim")) entao

   escreval ("Pode Passar!")

senao
     escreval("Nao pode passar!")
fimse


Fimalgoritmo